FROM python:3.13.1-slim-bullseye

# Change repository mirror and install dependencies
RUN apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    apt-get update -y && \
    apt-get install -y --fix-missing \
        python3-dev \
        default-libmysqlclient-dev \
        build-essential \
        pkg-config && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /appllm

# Copy source code
COPY src /appllm/src

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONPATH="${PYTHONPATH}:/appllm:/appllm/src"

# Expose port
EXPOSE 8081

# Copy and install dependencies
COPY requirements.txt /appllm
COPY requirements_sql_db.txt /appllm

RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install --no-cache-dir -r requirements_sql_db.txt