version: '3.8'

services:
  qdrant:
    image:
      qdrant/qdrant
    container_name: vector_database_qdrant
    ports:
      - "6333:6333"  # expose Qdrant on port 6333
    volumes:
      - qdrant_data:/qdrant/storage # define qrant_data for persistent data (/qdrant/storage is inside docker)
    restart: always  # Automatically restart if the container crashes

volumes:
  qdrant_data:
    